<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.yleoft</groupId>
    <artifactId>zVips</artifactId>
    <version>1.0.0</version>
    <description>VIP management gets easy</description>
    <url>https://github.com/yL3oft/zVips</url>
    <modules>
        <module>spigot</module>
        <module>velocity</module>
    </modules>
    <packaging>pom</packaging>

    <name>zVips</name>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <scm>
        <url>https://github.com/yL3oft/${project.name}</url>
        <connection>scm:git:git://github.com/yL3oft/${project.name}.git</connection>
        <developerConnection>scm:git:ssh://github.com:yL3oft/${project.name}.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <id>yleoft</id>
            <name>Leonardo Maehara</name>
            <email>maehara.leonardo@gmail.com</email>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <distributionManagement>
        <repository>
            <id>yl3oft</id>
            <url>https://repo.codemc.io/repository/yl3oft/</url>
        </repository>
    </distributionManagement>
</project>
